image: maven:3.6.3-jdk-11-slim

stages:
  - compile_stage
  - test_stage
  - package_stage

compile_job:
  stage: compile_stage
  script:
    - mvn clean compile

test_job:
  stage: test_stage
  script:
    - mvn test

package_job:
  stage: package_stage
  script:
    - mvn install