image: maven:latest

stages:
  - build
  - test
  - package

build:
  stage: build
  script:
    - mvn clean install

test:
  stage: test
  script:
    - mvn test

package:
  stage: package
  script:
    - mvn package